# YAML is case sensitive
# use spaces not a tab
apiVersion: apps/v1  # specify api to use for deployment
kind: Deployment  # kind of service/object you want to create
metadata:
  name: mongodb-deployment # name the deployment
spec:
  selector:
    matchLabels:
      db: mongodb  # look for this label/tag to match with k8 service
  template:
    metadata:
      labels:
        db: mongodb
      
    spec:
      containers:
      - name: mongodb
        image: mongo:8.2.5 # the image you created to run nginx in a container
        
        ports:
        - containerPort: 27017